version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ta_connect_db
      POSTGRES_USER: ta_connect_user
      POSTGRES_PASSWORD: ta_connect_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ta_connect_user -d ta_connect_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    security_opt:
      - seccomp=unconfined
      - label=disable

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/ta_connect/.env
    volumes:
      - ./backend/ta_connect:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/ta_connect
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend/ta_connect:/app
      - /app/node_modules
    depends_on:
      - backend
    security_opt:
      - seccomp=unconfined
      - label=disable

volumes:
  postgres_data: